
= BRIX11 generate documentation command

== Collection

common

== Usage

  brix11 [general options] generate documentation [options]

=== options

  -D, --doxygen                    Generate doxygen source documentation.
                                   Not generated by default.
  -N, --no-redirect                Do not redirect output from doxygen process..
                                   Default: run silent and hide output.

  -f, --force                      Force all tasks to run even if their dependencies do not require them to.
                                   Default: off
  -v, --verbose                    Run with increased verbosity level. Repeat to increase more.
                                   Default: 0

  -h, --help                       Show this help message.

== Description

Generate documentation from Asciidoctor sources into the 'docs' directory. To install
Asciidoctor with coderay support as gem run the following command

$ gem install asciidoctor:2.0.15 coderay

Installation of the *Doxygen* toolset is required to be able to generate doxygen source documentation.
When not available an error will be shown and no source documentation is generated.

When the *Graphviz* toolset is installed it will be used by doxygen to generate class inheritance graphs for
the doxygen source documentation otherwise the (simpler) integrated graph generation will be used.
